# Generated by Django 5.0.4 on 2024-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pmfdf',
            new_name='pmfdt',
        ),
    ]
